services:
  c-ookie-click:
    build: c-ookie-click
    restart: unless-stopped
    stop_grace_period: 1s
    environment:
      - LEADERBOARDDB=/data/leaderboard.db
      - PUBLICDIR=/site
    ports:
      - "127.0.0.1:2001:2001/tcp"
      - "127.0.0.1:8080:8080/tcp"
    volumes:
      - ./data:/data
      - ./public:/site:ro
      - /tmp/c.ookie.click:/tmp/c.ookie.click
  topekash:
    build: topekash
    restart: unless-stopped
    stop_grace_period: 1s
    volumes:
      - type: bind
        source: ./public/c.ookie.click/er/topeka
        target: /app/topeka
  backupdb:
    build: backupdb
    restart: unless-stopped
    stop_grace_period: 1s
    volumes:
      - ./data:/data
