services:
  c-ookie-click:
    build: c-ookie-click
    restart: unless-stopped
    stop_grace_period: 1s
    environment:
      - DBDIR=/data
      - PUBLICDIR=/site
    ports:
      - "127.0.0.1:2001:2001/tcp"
      - "127.0.0.1:8080:8080/tcp"
    volumes:
      - ./data:/data
      - ./public:/site:ro
      - /tmp/c.ookie.click:/tmp/c.ookie.click
